### ISSUE TITLE
Allow to use Ruby objects instead of noisy Node objects

### ISSUE THREAD

**Issue by ishikawa** [ishikawa/chelsy#2]
In current version, developers can use Ruby symbol literal to denote C identifier:

```ruby
Operator::Call.new(:printf, [Constant::String.new("Hello, World!\n")])
```

Instrad of using cumbersome AST object like this:

```ruby
Operator::Call.new(Ident.new(:printf), [Constant::String.new("Hello, World!\n")])
```

The latter is eye noisy, I (everybody?) like the former 😊 

However, it's halfway. I would make `Syntax::Constraint#ensure` to transform more Ruby objects to its `Chelsy::Node` counterparts.

So, the example above would be written as:

```ruby
Operator::Call.new(:printf, ["Hello, World!\n"])
```

## Caveats

- We can not use `String` to represent arbitrary C code snippet anymore. Add `Chelsy::Raw` node object and use it.
- For macro invocation, use `Symbol` or `Chelsy::Macro`.

## Todo

- [x] `String` to `Constant::String`
- [x] `Integer` to `Constant::Int`
- [x] `[type, symbol]` to `Param`
- [x] Add `Chelsy::Raw`
- [x] Add `Chelsy::Macro`
